import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "./_components/ModeToggle";
import AppProvider from "@/components/app-provider";
import { Toaster } from "@/components/ui/sonner";
import { NextIntlClientProvider } from "next-intl";
import SwitchLanguage from "@/components/switch-language";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { VideoTextDemo } from "@/components/VideoTextDemo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* next-intl */}
        <NextIntlClientProvider>
          {/* tanstack_query */}
          <AppProvider>
            {/* darkMode shadui */}
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <header className="sticky top-0 z-50 h-12 border-b border-b-gray-200 dark:border-b-gray-800 bg-background">
                <div className="container mx-auto flex h-full items-center justify-between">
                  <VideoTextDemo />
                  <div className="flex items-center gap-2 mr-4">
                    <SwitchLanguage />
                    <ModeToggle />
                  </div>
                </div>
              </header>

              <SidebarProvider>
                <AppSidebar />
                <main className="flex-1 container mx-auto">
                  <div className="flex items-center">
                    <SidebarTrigger />
                    <p>Do something!</p>
                  </div>
                  {children}
                </main>
              </SidebarProvider>
              <Toaster />
            </ThemeProvider>
          </AppProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
